# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d907851b5e9dc5b1439d4e1a8ff2cdba95a9d0fcda483ba969b9a07c8115d7a691b86fd775b84651f7e064baaef73aa4f044a2e1434e9537833bc1f452cb2583

test:
  secret_key_base: 881107b1d23b4c1f6461d7c573464c2a05beb1747b70b035d7d4ef085a687fcb3e5f4292611cdfa9ff3a575ebdf380c85afbe81442a6c9352f262f0947495f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
